# Includes complete Jenkins configuration in order to run croc-hunter pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  ImageTag: "2.74"
  Memory: "512Mi"
  AdminUser: admin
  AdminPassword: Azure12345678
  ServiceType: LoadBalancer
  ServicePort: 80
  InstallPlugins:
      - kubernetes:1.0
      - workflow-aggregator:2.5
      - credentials-binding:1.13
      - git:3.6.0
      - pipeline-github-lib:1.0
      - ghprb:1.39.0
      - blueocean:1.1.7
  NodeSelector: {beta.kubernetes.io/os: linux}
  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
    - "method java.util.Collection toArray"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]"
    - "staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object"

Agent:
  Enabled: true
  NodeSelector: {beta.kubernetes.io/os: linux}

rbac:
  install: true

Persistence:
  Enabled: false
#   StorageClass: "managed-standard"
#   AccessMode: ReadWriteOnce
#   Size: 32Gi
#   volumes:
# #  - name: nothing
# #    emptyDir: {}
#   mounts:
# #  - mountPath: /var/nothing
# #    name: nothing
# #    readOnly: true