apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/add-base-url: "true"
  name: ai-ingress
spec:
  rules:
    - host: {{ .Values.baseUrl }}
      http:
        paths:
          - path: /api/customvision/(.*)
            backend:
              serviceName: customvision-api
              servicePort: 80
          - path: /api/(.*)
            backend:
              serviceName: face-api
              servicePort: 80
          - path: /(.*)
            backend:
              serviceName: swagger
              servicePort: 80