apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-demo
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: kv
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-demo
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: "linkerd-localforwarder.linkerd-demo.svc.cluster.local:55678"
---
apiVersion: v1
kind: Namespace
metadata:
  name: canary
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr
---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: windows
---
apiVersion: v1
kind: Namespace
metadata:
  name: policy
