apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
spec:
  scaleTargetRef:
    deploymentName: bindingservicebus
  pollingInterval: 5
  cooldownPeriod:  15
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: {{ .Values.serviceBus.namespace }}
      queueName: binding
      queueLength: "2"
    authenticationRef:
        name: azure-servicebus-auth